# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html

stages:
  - test
  - deploy

test:
  image: python:3.7
  stage: test
  script:
    - cd ./moodify-raspi/gpioprogramming
    - python3 decodeTest.py

pages:
  image: alpine:latest

  stage: deploy
  script:
    - echo 'Runnning...'
  artifacts:
    paths:
      - public
  only:
    - master
