# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html
image: alpine:latest

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - apt-get install -y python-dev python-pip
    - cd ./moodify-raspi/gpioprogramming
    - python3 decodeTest.py

pages:
  stage: deploy
  script:
  - echo 'Runnning...'
  artifacts:
    paths:
    - public
  only:
  - master